#!/bin/bash
#
minute="$1"
hour="$2"
day="$3"
month="$4"
workingDir=$(pwd)
veveStarter="@reboot /usr/local/bin/veve-starter daemon-start > /media/share/veveshooter/tmp/veveshooter.log"

cd $workingDir
(crontab -l;echo "$minute $hour $day $month 1-5 veve-shoot-now") | crontab -
echo "$minute $hour $day $month 1-5 veve-shoot-now" >> ./data/crontab

exit 0